apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-configmap
data:
  DB_NAME: "coworkingdb"
  DB_USER: "tomuser"
  DB_PORT: "5432"
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  DB_PASSWORD: dG9tcGFzc3dvcmQ=